site_name: Estudos de Caso ANAC

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - neoteroi.cards
  - neoteroi.timeline
  - attr_list
  - md_in_html


nav:

  - Página inicial: index.md
  - Calliandra: 
      - Início: fases-caliandra/caliandra.md
      - Semear: fases-caliandra/semear.md
      - Germinar: fases-caliandra/germinar.md
      - Brotar: fases-caliandra/brotar.md
      - Florescer: fases-caliandra/florescer.md
      - Frutificar: fases-caliandra/frutificar.md
      - Amadurecer: fases-caliandra/amadurecer.md
      

  - Oficinas:
      - Início: case-studies/index.md
      - Casos: 
        - Diário de Bordo: case-studies/diario-bordo.md
        - HUB Financeiro: case-studies/hub-financeiro.md
        - ANAC e DECEA: case-studies/anac-decea.md
        - Safety Intelligence: case-studies/safety-Intelligence.md
        - Base de Aeronaves: case-studies/base-aeronaves.md
        - Matriz de Certificação: case-studies/matriz-certifica.md
        - Certifica 145: case-studies/certifica-145.md
  
  - Técnicas e Ferramentas: 
      - Início: tecnicas-e-ferramentas/index.md
      - Técnicas e Ferramentas: 
        - 5W2H: tecnicas-e-ferramentas/5w2h.md
        - Benchmarking: tecnicas-e-ferramentas/benchmarking.md
        - Blueprint de serviço: tecnicas-e-ferramentas/blueprint.md
        - Brainstorm: tecnicas-e-ferramentas/brainstorm.md
        - Canvas Co-desing: tecnicas-e-ferramentas/canvasCodesign.md
        - Canvas MVP: tecnicas-e-ferramentas/canvasMVP.md
        - Colcha de Retalhos: tecnicas-e-ferramentas/colchaDeRetalhos.md
        - Como Nós Podemos: tecnicas-e-ferramentas/comoNosPodemos.md
        - É – Não é – Faz – Não faz: tecnicas-e-ferramentas/eNaoFazNaoFaz.md
        - Feira e Caldeirão de Serviços: tecnicas-e-ferramentas/feira-caldeirao-servicos.md
        - Historia do Usuário: tecnicas-e-ferramentas/historiaUsuario.md
        - Hipótese do Negócio para o MVP: tecnicas-e-ferramentas/hipoteseDoNegocioParaMVP.md
        - Jornada do Usuário: tecnicas-e-ferramentas/JornadaDoUsuario.md
        - Método Disney: tecnicas-e-ferramentas/disneyAdaptado.md
        - Modelo de Matriz de Impacto e Esforço: matrizIPA.md
        - Personas: tecnicas-e-ferramentas/personas.md
        - Proposta do MVP: tecnicas-e-ferramentas/PropostaMVP.md
        - Quebra-gelo: tecnicas-e-ferramentas/quebra-gelo.md
        - Roadmap: tecnicas-e-ferramentas/Roadmap.md
        - Storyboard: tecnicas-e-ferramentas/storyboard.md
        - Testes Com Usuários: tecnicas-e-ferramentas/testesComUsuarios.md
        - Visão do Produto: tecnicas-e-ferramentas/visaoDoProduto.md
        - Wireframes: tecnicas-e-ferramentas/wireframe.md
        - World Café: tecnicas-e-ferramentas/worldCafe.md
        
        
        
    
        
  - Glossário: glossario/index.md
  


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para a preferência do sistema

  language: pt-BR
  favicon: assets/simbolo_itrac.png
  logo: assets/logo-itrac.png

extra:
  version:
    provider: mike

extra_css: 
  - stylesheets/style.css
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/neoteroi-cards.css
  - stylesheets/neoteroi-timeline.css
